server:
  rootPath: /api/*
  applicationContextPath: /
  adminContextPath: /admin
  applicationConnectors:
    - type: http
      port: 9092
  adminConnectors:
    - type: http
      port: 9093

database:
  driverClass: org.h2.Driver
  user: sa
#  password:
  url: jdbc:h2:./reviewdb
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
  
logging:
  level: INFO
  # Logger-specific levels.
  loggers:

    # Overrides the level of com.example.dw.Thing and sets it to DEBUG.
    "org.skife.jdbi.v2": TRACE
  appenders:
    - type: console
    
# Discovery-related settings.
discovery:
    serviceName: product-review